#!/bin/bash

startlocust() {
  echo 'Starting locust'
  locust -f /var/lib/jenkins/jobs/emif-fb/workspace/loadtests/db_listing.py -P 8090 --host=http://bioinformatics.ua.pt/emif-test &
}

stoplocust() {
  echo 'Stopping locust'
  kill `lsof -t -i:8090`
}

case "$1" in
  start)
    startlocust
    ;;
  stop)
    stoplocust
    ;;
  *)
    echo "Usage: $0 start|stop" >&2
    exit 3
    ;;
esac
